### ISSUE TITLE
Oodle decompression fails after the Steam client update on 2022-09-08

### ISSUE THREAD

**Issue by rivellathetank** [shalzuth/LostArkLogger#117]
- Opcodes are decoded correctly. (Expected.)
- Packets compression with `Snappy` or `None` are parsed correctly. (Expected.)
- Packets compressed with Oodle fail to get decompressed. (Unexpected.)

This started happening after the 2022-09-08 update.

**Comment by romkatv** [comment]
Fixed in https://github.com/shalzuth/LostArkLogger/commit/083e74aa2f4417ddbac2403e11a2e277c6b47a11. Thanks!
