### ISSUE TITLE
Incorrect information in readme

### ISSUE THREAD

**Issue by ooojustin** [shalzuth/LostArkLogger#14]
I noticed the guide in the readme states this: https://github.com/shalzuth/LostArkLogger/blob/d958a4192cf6700da77b35973697b4d164fcc622/README.md?plain=1#L25

For obvious reasons, some people do not want their packet dump uploaded anywhere and would prefer for the processing to occur locally. I see that you've accomplished this in the following commit: https://github.com/shalzuth/LostArkLogger/commit/bb031a93b6b94e6948afae6e55c0f41f401c27ae

So long as I'm not mistaken, I think you should update the readme and let people know that the packet data isn't leaving their PC. It may make some wary users feel safer. Just a thought, great work on this utility though.

**Comment by shalzuth** [comment]
Updated!
