### ISSUE TITLE
Issue with adding program to firewall

### ISSUE THREAD

**Issue by Toomodachi** [shalzuth/LostArkLogger#15]
Program already exist in Win11 firewall whitelist but the "This program needs to be added to Firewall!" error message keeps popping up when launching
![Screenshot_5](https://user-images.githubusercontent.com/104977843/166894373-20c3e684-8d42-45bc-970d-1b25ab7975c4.png)
![Screenshot_6](https://user-images.githubusercontent.com/104977843/166894491-4396520f-7db7-4ebe-816f-292ec501b240.png)
.

**Comment by derycklong** [comment]
same. my firewall is not even on to begin with.

**Comment by Henjuro** [comment]
You need to create a rule that allowes acces to Public Networks 
The code checking can be found here: https://github.com/shalzuth/LostArkLogger/blob/b5bacb8d1744540d4683edb5cfa232ebdbcdcb40/LostArkLogger/Program.cs#L35
