### ISSUE TITLE
Bard's Harp of Rythm get shown as own Entity

### ISSUE THREAD

**Issue by Henjuro** [shalzuth/LostArkLogger#19]
Bard's Harp of Rythem generate log messages like:
SOME_HEX_NUMBER,Night Fox Yoho,에고 하프 기본 공격,16903,1,0,0

에고 하프 기본 공격 means Harps basic attack
and so is counted towards a entity SOME_HEX_NUMBER instead of the person that placed the harp.
Not sure if this can even be fix with how the data is currently aquired, especially for instances where there is multiple Bards.

**Comment by shalzuth** [comment]
Thanks for the bug report - minions like this and the artilerrist turret need be some linked. Will add to backlog

**Comment by shalzuth** [comment]
fixed by 43ccc4696d296e496143b577d07dc3647ddbf468
