### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by shnok** [shalzuth/LostArkLogger#28]
AccessViolationException not caught at line 56 in Oodle.cs

`if (!OodleNetwork1UDP_Decode(oodleState, oodleSharedDict, payload, payload.Length, tempPayload, oodleSize))`

I happens randomly (much faster when lots of players)

**Comment by shalzuth** [comment]
fixed by 015ebb481c1e34d9753f381fc669850c2fa30ed2
