### ISSUE TITLE
Breakdown of Skills

### ISSUE THREAD

**Issue by Thork8** [shalzuth/LostArkLogger#42]
Hi, awsome tool, not gona lie.

what i noticed, when i break down the skills, its only limited to 8 highest entries even if i drag the overlay box larger.
if i use auto attacks and ultimate + Bleed gem + 8 skills on the hobar, would love to see all dmg sources and not just the 8 highest.

keep up the awsome work!

**Comment by shalzuth** [comment]
fixed by 393d60b26c89017e0f4420fca00b9f643774598d
