### ISSUE TITLE
NPC dmg should not be displayed in the main screen of the meter

### ISSUE THREAD

**Issue by omonoiatis9** [shalzuth/LostArkLogger#49]
NPC is defined as any mob/boss/monster other than the players. Currently boss damage also shows up on the meter, skewing the percentages of the dmg done by players.
![boss](https://user-images.githubusercontent.com/20650844/167315651-4b93e0fa-f7e3-44d3-8727-875df999f1cc.png)

It would be better to have all dmg done to players by NPCs in a separate tab that looks very similar to the main dps tab, maybe called "Damage Taken", and perhaps be able to choose if you want the bar chart in ascending or descending order (reason for maybe wanting it in ascending order is so that being at the "top" of each type of chart is always the good position - most dmg done, least dmg taken)

**Comment by shalzuth** [comment]
Fixed by 33c272989dd7f8124a8222a3602d17482b92b497 , but no configurable way to see NPC damage yet.
