### ISSUE TITLE
The meters should not automatically reset without the user's consent on each loading screen

### ISSUE THREAD

**Issue by omonoiatis9** [shalzuth/LostArkLogger#51]
Possible ways to deal with this:

1. Give the user the option to check/uncheck a box for "autoclearing meters on loadup" - possibly with a configurable delay
2. Always autoclear after X seconds from the time you load, but during those 5 seconds have a clickable "cancel" button that fades away eventually. (idea from Eren's UI").

Both 1 and 2 would also require a manual "clear" button.

**Comment by shalzuth** [comment]
Maybe solved by 33c272989dd7f8124a8222a3602d17482b92b497
It doesn't clear anymore, unless you start a fight in a new load screen.
Encounter info is preserved.

**Comment by omonoiatis9** [comment]
Can be marked as solved. Options 1 and 2 are just nice to have customizations, but the issue as a whole can be closed. The current implementation is i think the default behavior of most dps meters and pretty acceptable.
